// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nokelnztvnutfynfiegj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5va2Vsbnp0dm51dGZ5bmZpZWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODI4MTEsImV4cCI6MjA1ODg1ODgxMX0.WyUkL4Ku89J4M3PKiGpC_wDW1BZAIziw4jH86h0YnW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);